.data 
	msg: .asciiz  "\n\n________PRESIDENTES_______\n"
	msg1: .asciiz  "\nRAPAZ - 11111\nCARLIM - 22222\nNANDIN - 33333\nBRANCO - 77777"
	msg2: .asciiz "\nVOTO COMPUTADO COM SUCESSO!"
	msg3: .asciiz "\nESCOLHA: "
	
	msg4: .asciiz "\n__________________________\n"
	msg5: .asciiz "\nRAPAZ: "
	msg6: .asciiz "\nCARLIM: "
	msg71: .asciiz "\nNANDIN: "
	
	msg7: .asciiz "VOTO ANULADO!\n"
	
	msg8: .asciiz "\nVOTOS TOTAIS:"
	msg9: .asciiz "\nVOTOS NULOS:"
	
	msg10: .asciiz "\n\n________DEPUTADOS_______\n"
	msg11: .asciiz "\nHEMAN - 44444\nPEDRO - 55555\nALEX - 66666\nBRANCO - 77777"
	
	msg12: .asciiz "\nHEMAN: "
	msg13: .asciiz "\nPEDRO: "
	msg14: .asciiz "\nALEX: "
	msg15: .asciiz "\nBrancos: "
.text
		# CONTADOR GERAL
	la $s0,0 # LOAD ADDRESS, FAZ COM QUE O COMPUTADOR SETE O REGISTRADOR $s0 COM O VALOR ZERO PARA OS VOTOS NULOS.
	la $s7,0 # LOAD ADDRESS, FAZ COM QUE O COMPUTADOR SETE O REGISTRADOR $s7 COM O VALOR ZERO PARA OS VOTOS EM BRANCO.
		
		# CONTADORES PARA PRESIDENTE
  	
  	la $s1,0 # LOAD ADDRESS, FAZ COM QUE O REGISTRADOR $s1 FIQUE SETADO COM O VALOR 0, PARA USAR COMO CONTADOR PARA O CANDIDATO ''RAPAZ''
  	la $s2,0 # LOAD ADDRESS, FAZ COM QUE O REGISTRADOR $s2 FIQUE SETADO COM O VALOR 0, PARA USAR COMO CONTADOR PARA O CANDIDATO ''CARLIM''
  	la $s3,0 # LOAD ADDRESS, FAZ COM QUE O REGISTRADOR $s3 FIQUE SETADO COM O VALOR 0, PARA USAR COMO CONTADOR PARA O CANDIDATO ''NANDIN''	
  		
  		# CONTADORES PARA DEPUTADOS
  	
  	la $s4,0 # LOAD ADDRESS, FAZ COM QUE O REGISTRADOR $s4 FIQUE SETADO COM O VALOR 0, PARA USAR COMO CONTADOR PARA O CANDIDATO ''HEMAN''
  	la $s5,0 # LOAD ADDRESS, FAZ COM QUE O REGISTRADOR $s4 FIQUE SETADO COM O VALOR 0, PARA USAR COMO CONTADOR PARA O CANDIDATO ''PEDRO''
  	la $s6,0 # LOAD ADDRESS, FAZ COM QUE O REGISTRADOR $s4 FIQUE SETADO COM O VALOR 0, PARA USAR COMO CONTADOR PARA O CANDIDATO ''ALEX''



presidente:
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS. 
	la $a0,msg # CARREGO O CONTEÚDO DA STRING '____PRESIDENTES___' PARA O REGISTRADOR DE ARGUMENTO $a0.
	syscall # CHAMO O SISTEMA PARA EXECUTAR AS DUAS LINHAS PARA IMPRIMI-LAS NO PROMPT.
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS.
	la $a0,msg1 # CARREGO O CONTEÚDO DA STRING 'msg1' PARA O REGISTRADOR DE ARGUMENTO $a0.
	syscall # CHAMO O SISTEMA PARA EXECUTAR AS DUAS LINHAS PARA IMPRIMI-LAS NO PROMPT
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS.
	la $a0,msg3 # CARREGO O CONTEÚDO DA STRING 'msg3' PARA O REGISTRADOR DE ARGUMENTO $a0.
	syscall # CHAMO O SISTEMA PARA EXECUTAR AS DUAS LINHAS PARA IMPRIMI-LAS NO PROMPT
	
	li $v0,5 # CHAMO A FUNÇÃO QUE CUIDA DA LEITURA DE INTEIROS EM MIPS. EQUIVALENTE A O SCANF DA LINGUAGEM EM C. 
	syscall  # CHAMO O SISTEMA ONDE O CÓDIGO ESPERA O USUÁRIO DIGITAR ALGUM INTEIRO.
	
	move $t1,$v0  	# PEGO O CONTEÚDO LIDO QUE ESTÁ NO REGISTRADOR $v0 E MOVO PARA UM REGISTRADOR TEMPORARIO $t1.
	# MOVENDO PARA $t1 AGORA POSSO TRATAR OS DADOS USANDO INSTRUÇÕES DE CONDIÇÃO.
	
	beq $t1,11111,L1 # COMANDO 'beq' QUE COMPARA O CONTEÚDO DO REGISTRADOR $t1 COM A CONSTANTE QUE EU SETEI
	# QUE NO CASO É O INTEIRO 11111, CASO ESSES CONTEÚDOS FOREM 
	# IGUAIS ELE PAUSA O PROCESSO DA FUNÇÃO 'presidente' E  VAI PARA A FUNÇÃO ' L1 ' que está abaixo.
	
	
	beq $t1,22222,L2 # COMANDO 'beq' QUE COMPARA O CONTEÚDO DO REGISTRADOR $t1 COM A CONSTANTE QUE EU SETEI
	# QUE NO CASO É O INTEIRO 22222, CASO ESSES CONTEÚDOS FOREM 
	# IGUAIS ELE PAUSA O PROCESSO DA FUNÇÃO 'presidente' E  VAI PARA A FUNÇÃO ' L2 ' que está abaixo.
	
	beq $t1,33333,L3 # COMANDO 'beq' QUE COMPARA O CONTEÚDO DO REGISTRADOR $t1 COM A CONSTANTE QUE EU SETEI
	# QUE NO CASO É O INTEIRO 33333, CASO ESSES CONTEÚDOS FOREM 
	# IGUAIS ELE PAUSA O PROCESSO DA FUNÇÃO 'presidente' E  VAI PARA A FUNÇÃO ' L3 ' que está abaixo.
	
	beq $t1,77777,L7 # COMANDO 'beq' QUE COMPARA O CONTEÚDO DO REGISTRADOR $t1 COM A CONSTANTE QUE EU SETEI
	# QUE NO CASO É O INTEIRO 77777, CASO ESSES CONTEÚDOS FOREM 
	# IGUAIS ELE PAUSA O PROCESSO DA FUNÇÃO 'presidente' E  VAI PARA A FUNÇÃO ' L7 ' que está abaixo.
	
	beq $t1,00000,fim # COMANDO 'beq' QUE COMPARA O CONTEÚDO DO REGISTRADOR $t1 COM A CONSTANTE QUE EU SETEI
	# QUE NO CASO É O INTEIRO 77777, CASO ESSES CONTEÚDOS FOREM 
	# IGUAIS ELE PAUSA O PROCESSO DA FUNÇÃO 'presidente' E  VAI PARA A FUNÇÃO ' fim ' que está abaixo.
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
	la $a0,msg7 # CASO NENHUMA CONDIÇÃO ACIMA SEJA SATISFEITA, O CÓDIGO É CONTINUADO. AQUI MOSTRARÁ QUE O VOTO FOI ANULADO.
	syscall # CHAMO O SISTEMA PARA EXECUTAR AS DUAS LINHAS PARA IMPRIMI-LAS NO PROMPT
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
	la $a0,msg4 # AQUI É APENAS UM ESPAÇAMENTO, REFERENTE A STRING ' __________ ' 
	syscall # CHAMO O SISTEMA PARA EXECUTAR AS DUAS LINHAS PARA IMPRIMI-LAS NO PROMPT
	
	add $s0,$s0,1 # FAZ O INCRIMENTO DO REGISTRADOR $s1 QUE CONTA OS VOTOS NULOS.
	
	j deputado # COMANDO QUE FAZ O CÓDIGO PULAR PARA A FUNÇÃO INDICADA.
	
			L1:
				add $s1,$s1,1	# INCREMENTA O CONTADOR RESPONSÁVEL PELOS VOTOS NO CANDIDATO ' RAPAZ '
				
				li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
				la $a0,msg2 # IMPRESSÃO DA STRING INFORMANDO O USUÁRIO QUE O VOTO FOI COMPUTADO.
				syscall # CHAMO O SISTEMA PARA EXECUTAR AS DUAS LINHAS PARA IMPRIMI-LAS NO PROMPT
				
				li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE SRINGS
				la $a0,msg4 # IMPRESSÃO DA STRING QUE SERVE COMO ESPAÇAMENTO
				syscall # CHAMO O SISTEMA PARA EXECUTAR AS DUAS LINHAS PARA IMPRIMI-LAS NO PROMPT
				
				j deputado # COMANDO QUE FAZ O CÓDIGO PULAR PARA A FUNÇÃO INDICADA.

			L2:
				add $s2,$s2,1 # INCREMENTA O CONTADOR RESPONSÁVEL PELOS VOTOS NO CANDIDATO ' CARLIM '
				
				li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
				la $a0,msg2 # IMPRESSÃO DA STRING INFORMANDO O USUÁRIO QUE O VOTO FOI COMPUTADO.
				syscall # CHAMO O SISTEMA PARA EXECUTAR AS DUAS LINHAS PARA IMPRIMI-LAS NO PROMPT
				
				li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
				la $a0,msg4 # IMPRESSÃO DA STRING QUE SERVE COMO ESPAÇAMENTO
				syscall # CHAMO O SISTEMA PARA EXECUTAR AS DUAS LINHAS PARA IMPRIMI-LAS NO PROMPT
				
				j deputado # COMANDO QUE FAZ O CÓDIGO PULAR PARA A FUNÇÃO INDICADA.
			
			L3:
				add $s3,$s3,1 # INCREMENTA O CONTADOR RESPONSÁVEL PELOS VOTOS NO CANDIDATO ' NANDIN '
				
				li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
				la $a0,msg2 # IMPRESSÃO DA STRING INFORMANDO O USUÁIRO QUE O VOTO FOI COMPUTADO.
				syscall # CHAMO O SISTEMA PARA EXECUTAR AS DUAS LINHAS PARA IMPRIMI-LAS NO PROMPT
				
				li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS.
				la $a0,msg4 # IMPRESSÃO DA STRING COM FINALIDADE DE QUEBRA DE LINHA
				syscall # CHAMO O SISTEMA PARA EXECUTAR AS DUAS LINHAS PARA IMPRIMI-LAS NO PROMPT
				j deputado # COMANDO QUE FAZ O CÓDIGO PULAR PARA A FUNÇÃO INDICADA.
					
			L7:
				add $s7,$s7,1 # INCREMENTA O CONTADOR RESPONSÁVEL PELOS VOTOS EM BRANCO.
				
				li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
				la $a0,msg2 # IMPRESSÃO DA STRING INFORMANDO O USUÁRIO QUE O VOTO FOI COMPUTADO
				syscall # CHAMO O SISTEMA PARA EXECUTAR AS DUAS LINHAS PARA IMPRIMI-LAS NO PROMPT
				
				li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
				la $a0,msg4 # IMPRESSÃO DA STRING COM FINALIADDE DE QUEBRA DE LINHA
				syscall # CHAMADA DO SISTEMA PARA EXECUÇÃO
				
				j deputado # JUMP PARA A FUNÇÃO DEPUTADO, LOGO ABAIXO.
deputado:
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
	la $a0,msg10 # IMPRESSÃO DA STRING DEFINIDA NO BLOCO '.data'
	syscall # CHAMADA DO SISTEMA.
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃMO DE STRINGS.
	la $a0,msg11 # IMPRESSÃO DA STRING DEFINIDA NO BLOCO '.data'
	syscall # CHAMADA DO SISTEMA
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS.
	la $a0,msg3  # IMPRESSÃO DA STRING DEFINIDA NO BLOCO '.data'
	syscall # CHAMADA DO SISTEMA
	
	li $v0,5 # CHAMO A FUNÇÃO DE LEITURA DE INTEIROS.
	syscall # CHAMADA DO SISTEMA
	
	move $t1, $v0 # MOVO O INTEIRO LIDO PARA O REGISTRADOR TEMPORARIO $t1
	
	beq $t1,44444,L4 # IRÁ COMPARAR A VARIAVEL LIDA COM O NUMERO DESEJADO, QUE NO CASO É 44444. SE FOR VERDADE, O PROGRAMA IRÁ PULAR PARA A FUNÇÃO L4, QUE ESTÁ LOGO ABAIXO.
	beq $t1,55555,L5 # IRÁ COMPARAR A VARIAVEL LIDA COM O NUMERO DESEJADO, QUE NO CASO É 55555. SE FOR VERDADE, O PROGRAMA IRÁ PULAR PARA A FUNÇÃO L5, QUE ESTÁ LOGO ABAIXO.
	beq $t1,66666,L6 # IRÁ COMPARAR A VARIAVEL LIDA COM O NUMERO DESEJADO, QUE NO CASO É 66666. SE FOR VERDADE, O PROGRAMA IRÁ PULAR PARA A FUNÇÃO L6, QUE ESTÁ LOGO ABAIXO.
	beq $t1,77777,L8 # IRÁ COMPARAR A VARIAVEL LIDA COM O NUMERO DESEJADO, QUE NO CASO É 77777. SE FOR VERDADE, O PROGRAMA IRÁ PULAR PARA A FUNÇÃO L8, QUE ESTÁ LOGO ABAIXO.
	beq $t1,00000,fim # IRÁ COMPARAR A VARIAVEL LIDA COM O NUMERO DESEJADO, QUE NO CASO É 00000. SE FOR VERDADE, O PROGRAMA IRÁ PULAR PARA A FUNÇÃO fim, QUE ESTÁ LOGO ABAIXO.
	
	# CASO NENHUM 'beq' SEJA SATISFEITO, O PROGRAMA IRÁ CONTINUAR O CÓDIGO, O QUE SIGNIFICA QUE O USUÁRIO ANULOU O VOTO.
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS.
	la $a0,msg7 # IMPRESSÃO DA STRING DEFINIDA NO BLOCO '.data'
	syscall # CHAMADA DO SISTEMA
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS.
	la $a0,msg4 # IMPRESSÃO DA STRING DEFINIDA NO BLOCO '.data'
	syscall # CHAMADA DO SISTEMA
	
	add $s0,$s0,1 # INCREMENTO DO CONTADOR REFERENTE AO VOTOS NULOS.
	j presidente # JUMP PARA A FUNÇÃO PRESIDENTE LOGO ACIMA.
	
		
			L4: # FUNÇÃO L4.
				add $s4,$s4,1 # INCREMENTO DO CONTADOR REFERENTE AO CANDIDATO HEMAN.
				
				li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS.
				la $a0,msg2 # STRING A SER IMPRIMIDA.
				syscall # CHAMADA DO SISTEMA
				
				li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS.
				la $a0,msg4 # STRING A SER IMPRIMIDA.
				syscall # CHAMADA DO SISTEMA
				
				j presidente # JUMP PARA A FUNÇÃO PRESIDENTE.
			
			L5: # FUNÇÃO L5
				add $s5,$s5,1 # INCREMENTO DO CONTADOR REFERENTE AO CANDIDATO PEDRO
				
				li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
				la $a0,msg2 # STRING A SER IMPRIMIDA.
				syscall # CHAMADA DO SISTEMA
				
				li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
				la $a0,msg4 # STRING A SER IMPRIMIDA.
				syscall # CHAMADA DO SISTEMA
				
				j presidente # JUMP PARA FUNÇÃO PRESIDENTE.
			
			L6: # FUNÇÃO L6
				add $s6,$s6,1 # INCREMENTO DO CONTADOR REFERENTE AO CANDIDATO ALEX
				
				li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS.
				la $a0,msg2 # STRING A SER IMPRIMIDA.
				syscall # CHAMADA DO SISTEMA
				
				li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS.
				la $a0,msg4 # STRING A SER IMPRIMIDA.
				syscall # CHAMADA DO SISTEMA
				
				j presidente # JUMP PARA A FUNÇÃO PRESIDENTE
				
			
			L8: # FUNÇÃO L8
				add $s7,$s7,1 # INCREMENTO DO CONTADOR REFERENTE AOS VOTOS BRANCOS
				
				li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS;
				la $a0,msg2 # STRING A SER IMPRIMIDA
 				syscall # CHAMADA DO SISTEMA
				
				li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
				la $a0,msg4 # STRING A SER IMPRIMIDA
				syscall # CHAMADA DO SISTEMA
				
				j presidente # JUMP PARA A FUNÇÃO PRESIDENTE
				
				
		
fim:
	# PRESIDENTES 
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
	la $a0,msg # INFORMAÇÃO DOS PRESIDENTES
	syscall # CHAMADA DO SISTEMA
	
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
	la $a0,msg5 # IMPRESSÃO DA STRING DO CANDIDATO A PRESIDENTE: RAPAZ.
	syscall # CHAMADA DO SISTEMA
	
	li $v0,1 # CHAMO A FUNÇÃO DE IMPRESSÃO DE INTEIROS.
	move $a0,$s1 # PEGO O INTEIRO NO ENDEREÇO $s1 E CARREGO ELE PARA O REGISTRADOR DE ARGUMENTO, ONDE IRÁ MOSTRAR O INTEIRO REFERENTE AO NUMERO DE VOTOS EM ' RAPAZ '
	syscall # CHAMADA DO SISTEMA
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
	la $a0,msg6 # IMPRESSÃO DA STRING SOBRE O CANDIDATO A PRESIDENTE: CARLIM.
	syscall # CHAMADA DO SISTEMA
	
	li $v0,1 # CHAMO A FUNÇÃO DE IMPRESSÃO DE INTEIROS
	move $a0,$s2 # PEGO O INTEIRO NO ENDEREÇO $s2 E CARREGO ELE PARA O REGISTRADOR DE ARGUMENTO, ONDE IRÁ MOSTRAR O INTEIRO REFERENETE AO NUMERO DE VOTOS EM ' CARLIM '
	syscall # CHAMADA DO SISTEMA
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
	la $a0,msg71 # STRING A SER IMPRIMIDA, REFERENTE AO CANDIDATO: NANDIN.
	syscall # CHAMADA DO SISTEMA
	
	li $v0,1 # CHAMO A FUNÇÃO DE IMPRESSÃO DE INTEIROS
	move $a0,$s3 # PEGO O INTEIRO NO ENDEREÇO $s3 E CARREGO ELE PARA O REGISTRADOR DE ARGUMENTO, ONDE IRÁ MOSTRAR O INTEIRO REFERENTE AO NUMERO DE VOTOS EM ' NANDIN '
	syscall # CHAMADA DO SISTEMA
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
	la $a0,msg4 # STRING A SER IMPRESSA DEFINIDA NO '.data'
	syscall # CHAMADA DO SISTEMA
	
	# DEPUTADOS:
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
	la $a0,msg10 # STRING A SER IMPRIMIDA DEFINIDA NO ' .data '
	syscall # CHAMADA DO SISTEMA.
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
	la $a0,msg12 # STRING A SER IMPRIMIDA DEFINIDA NO ' .data '
	syscall # CHAMADA DO SISTEMA.
	
	li $v0,1 # CHAMO A FUNÇÃO DE IMPRESSÃO DE INTEIROS
	move $a0,$s4 # PEGO O INTEIRO QUE ESTÁ NO ENDEREÇO $s4 E CARREGO PARA O REGISTRADOR DE ARGUMENTO.
	syscall # CHAMADA DO SISTEMA
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
	la $a0,msg13 # STRING A SER IMPRESSA.
	syscall # CHAMADA DO SISTEMA
	
	li $v0,1 # CHAMO A FUNÇÃO DE IMPRESSÃO DE INTEIROS
	move $a0,$s5 # PEGO O INTEIRO QUE ESTÁ NO ENDEREÇO $s4 E CARREGO PARA O REGISTRADOR DE ARGUMENTO.
	syscall # CHAMADA DO SISTEMA.
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
	la $a0,msg14 # STRING A SER IMPRESSA.
	syscall # CHAMADA DO SISTEMA
	
	li $v0,1 # CHAMO A FUNÇÃO DE IMPRESSÃO DE INTEIROS
	move $a0,$s6 # INTEIRO A SER IMPRESSO.
	syscall # CHAMADA DO SISTEMA
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
	la $a0,msg4 # STRING QUE TRATA APENAS DO ESPAÇAMENTO ENTRE AS LINHAS. ESTÉTICA.
	syscall # CHAMADA DO SISTEMA
	
	# VOTOS GERAIS
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
	la $a0,msg8 # IMPRESSÃO DA STRING QUE REFERE-SE AOS VOTOS TOTAIS. 
	syscall # CHAMADA DO SISTEMA
	
	add $t4,$s1,$s2 # JOGO A SOMA DOS CONTADORES $S1 E $S2 PARA O REG $T4
	add $t5,$t4,$s0 # PEGO O $T4 E SOMO COM O REG $S0 E ARMAZENO EM $T5
	add $t6,$t5,$s3	# SOMO $T5 COM $S3 E ARMAZENO EM $T6
	add $t4,$t6,$s4 # SOMO $T6 COM $S4 E ARMAZENO EM $T4
	add $t5,$t4,$s5 # SOMO $T4 COM $S5 E ARMAZENO EM $T5
	add $t6,$t5,$s6 # SOMO $T5 COM $S6 E ARMAZENO EM $T6
	add $t5,$t6,$s7 # SOMO $T6 COM $S7 E ARMAZENO EM $T5
	
	li $v0,1 # CHAMO A FUNÇÃO DE IMPRESSÃO DE INTEIROS
	move $a0,$t5	 # IMPRESSÃO DAS SOMAS, RESULTANDO NOS VOTOS TOTAIS.
	syscall # CHAMADA DO SISTEMA
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
	la $a0,msg9 # IMPRESSÃO DA STRING ' VOTOS NULOS '
	syscall # CHAMADA DO SISTEMA
	
	li $v0,1 # CHAMO A FUNÇÃO DE IMPRESSÃO DE INTEIROS
	move $a0,$s0 # IMPRESSÃO DO INTEIRO QUE INFORMA A QUANTIDADE DE VOTOS NULOS.
	syscall # CHAMADA DO SISTEMA
	
	li $v0,4 # CHAMO A FUNÇÃO DE IMPRESSÃO DE STRINGS
	la $a0,msg15 # IMPRESSÃO DA STRING DEFINIDA EM '.DATA'
	syscall # CHAMADA DO SISTEMA
	
	li $v0,1 # CHAMO A FUNÇÃO DE IMPRESSÃO DE INTEIROS
	move $a0,$s7 # INTEIRO A SER IMPRESSO.
	syscall # CHAMADA DO SISTEMA
	
	#FIM DA URNA ELETRONICA.
	
